<?php

// You can also add your custom configuration. Just add the path to your custom
// configuration file to the environment variable `TYPO3_EXCLUDE_FROM_PACKAGING`
// and make sure the file returns an array with the keys `directories` and `files`
// on root level.

// Note: The filter is case-insensitive. There is furthermore no need to define the
// filenames with / without a leading dot. This is taken into account automatically.

return [
    'directories' => [
        '.build',
        '.ddev',
        '.git',
        '.github',
        '.gitlab',
        '.gitlab-ci',
        '.idea',
        '.phive',
        'bin',
        'build',
        'public',
        'tailor-version-artefact',
        'tailor-version-upload',
        'tests',
        'tools',
        'vendor',
    ],
    'files' => [
        'bitbucket-pipelines.yaml',
        'bitbucket-pipelines.yml',
        'bower.json',
        'CODE_OF_CONDUCT.md',
        'codeception.yaml',
        'codeception.yml',
        'composer.lock',
        'crowdin.yaml',
        'crowdin.yml',
        'deploy.yaml',
        'deploy.yml',
        'docker-compose.yaml',
        'docker-compose.yml',
        'Dockerfile',
        'DS_Store',
        'dynamicReturnTypeMeta.json',
        'ecs.php',
        'editorconfig',
        'env',
        'env.dist',
        'eslintignore',
        'eslintrc.json',
        'ExtensionBuilder.json',
        'fractor.php',
        'gitattributes',
        'gitignore',
        'gitlab-ci.yaml',
        'gitlab-ci.yml',
        'gitmodules',
        'gitreview',
        'Makefile',
        'nvmrc',
        'package-lock.json',
        'package.json',
        'phive.xml',
        'php-cs-fixer.dist.php',
        'php-cs-fixer.php',
        'php_cs',
        'php_cs.php',
        'phpcs.xml',
        'phpcs.xml.dist',
        'phplint.yml',
        'phpstan-baseline.neon',
        'phpstan.neon',
        'phpstan.neon.dist',
        'phpstorm.meta.php',
        'phpunit.xml',
        'phpunit.xml.dist',
        'prettierrc.json',
        'rector.php',
        'renovate.json',
        'scrutinizer.yml',
        'styleci.yml',
        'stylelint.config.js',
        'stylelintrc',
        'travis.yml',
        'tslint.yaml',
        'tslint.yml',
        'typoscript-lint.yaml',
        'typoscript-lint.yml',
        'typoscriptlint.yaml',
        'typoscriptlint.yml',
        'webpack.config.js',
        'webpack.mix.js',
        'yarn.lock',
    ],
];
