name: tests
on: [push, pull_request]
jobs:
  tests:
    name: Tests with PHP${{ matrix.php }}
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        php: ["7.2", "7.3", "7.4", "8.0", "8.1", "8.2"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: zip
          tools: composer:v2

      - name: Get composer cache directory
        id: composer-cache
        run: echo "composer_cache_dir=$(composer config cache-files-dir)" >> $GITHUB_ENV

      - name: Cache composer dependencies
        uses: actions/cache@v3
        with:
          path: ${{ env.composer_cache_dir }}
          key: ${{ runner.os }}-php-${{ matrix.php }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-php-${{ matrix.php }}-composer-

      - name: Install dependencies
        if: ${{ matrix.php <= '8.1' }}
        run: composer install --prefer-dist --no-progress --no-suggest --optimize-autoloader

      - name: Install dependencies PHP 8.2
        # @todo: Needed until prophecy (req by phpunit) allows PHP 8.2, https://github.com/phpspec/prophecy/issues/556
        if: ${{ matrix.php > '8.1' }}
        run: composer install --prefer-dist --no-progress --no-suggest --optimize-autoloader --ignore-platform-req=php+

      - name: Run cgl
        if: ${{ matrix.php < '8.1' }}
        run: composer cs

      - name: Run unit tests
        run: composer tests:unit
